const mockData = [
  {
    tenant_id: 1,
    first_name: "Kyra",
    last_name: "Thompson",
    date_of_birth: "03/23/1992",
    nationality: "Mexican",
    address: {
      country: "United States",
      state: "California",
      city: "San Diego",
      postal_code: "07052",
    },
    identification_number: "NBA44444444",
    email: "kyrie@nets.com",
    phone_number: "+15444444444",
    emergency_contact: {
      first_name: "Sam",
      last_name: "Smith",
      phone_number: "+16123332222",
    },
    room_numbers: [11, 15, 9],
    check_in: "01/13/2024",
    check_out: "03/18/2024",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 650,
    vehicle: {
      make: "Porsche",
      model: "911",
      plate_number: "NPJ 753",
    },
  },
  {
    tenant_id: 1,
    first_name: "John",
    last_name: "Doe",
    date_of_birth: "05/10/1990",
    nationality: "Canadian",
    address: {
      country: "United States",
      state: "New York",
      city: "New York",
      postal_code: "10001",
    },
    identification_number: "CAN12345678",
    email: "john@doe.com",
    phone_number: "+15555555555",
    emergency_contact: {
      first_name: "Jane",
      last_name: "Doe",
      phone_number: "+15556667777",
    },
    room_numbers: [21, 22],
    check_in: "02/20/2023",
    check_out: "05/01/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1200,
    vehicle: {
      make: "Tesla",
      model: "Model S",
      plate_number: "TES 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Emma",
    last_name: "Stone",
    date_of_birth: "11/06/1988",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90001",
    },
    identification_number: "USA87654321",
    email: "emma@stone.com",
    phone_number: "+16667778888",
    emergency_contact: {
      first_name: "Andrew",
      last_name: "Garfield",
      phone_number: "+16669990000",
    },
    room_numbers: [30],
    check_in: "06/15/2023",
    check_out: "08/20/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 900,
    vehicle: {
      make: "BMW",
      model: "X5",
      plate_number: "BMW 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Michael",
    last_name: "Jordan",
    date_of_birth: "02/17/1963",
    nationality: "American",
    address: {
      country: "United States",
      state: "Illinois",
      city: "Chicago",
      postal_code: "60616",
    },
    identification_number: "USA99988877",
    email: "michael@jordan.com",
    phone_number: "+14443332222",
    emergency_contact: {
      first_name: "Scottie",
      last_name: "Pippen",
      phone_number: "+14446665555",
    },
    room_numbers: [7, 8, 9],
    check_in: "03/10/2023",
    check_out: "07/15/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 750,
    vehicle: {
      make: "Mercedes",
      model: "S-Class",
      plate_number: "MBZ 456",
    },
  },
  {
    tenant_id: 1,
    first_name: "Taylor",
    last_name: "Swift",
    date_of_birth: "12/13/1989",
    nationality: "American",
    address: {
      country: "United States",
      state: "Tennessee",
      city: "Nashville",
      postal_code: "37201",
    },
    identification_number: "USA11122233",
    email: "taylor@swift.com",
    phone_number: "+17778889999",
    emergency_contact: {
      first_name: "Austin",
      last_name: "Swift",
      phone_number: "+17770001111",
    },
    room_numbers: [45, 46],
    check_in: "09/01/2023",
    check_out: "11/30/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1300,
    vehicle: {
      make: "Audi",
      model: "A8",
      plate_number: "AUD 321",
    },
  },
  {
    tenant_id: 1,
    first_name: "Chris",
    last_name: "Evans",
    date_of_birth: "06/13/1981",
    nationality: "American",
    address: {
      country: "United States",
      state: "Massachusetts",
      city: "Boston",
      postal_code: "02101",
    },
    identification_number: "USA55566677",
    email: "chris@evans.com",
    phone_number: "+18889990000",
    emergency_contact: {
      first_name: "Scott",
      last_name: "Evans",
      phone_number: "+18880002222",
    },
    room_numbers: [12],
    check_in: "05/22/2023",
    check_out: "09/12/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1100,
    vehicle: {
      make: "Chevrolet",
      model: "Impala",
      plate_number: "CHE 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Jennifer",
    last_name: "Lawrence",
    date_of_birth: "08/15/1990",
    nationality: "American",
    address: {
      country: "United States",
      state: "Kentucky",
      city: "Louisville",
      postal_code: "40201",
    },
    identification_number: "USA33344455",
    email: "jennifer@lawrence.com",
    phone_number: "+19991112222",
    emergency_contact: {
      first_name: "Blaine",
      last_name: "Lawrence",
      phone_number: "+19990003333",
    },
    room_numbers: [3, 4],
    check_in: "11/10/2023",
    check_out: "02/20/2024",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 800,
    vehicle: {
      make: "Ford",
      model: "Explorer",
      plate_number: "FRD 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Robert",
    last_name: "Downey Jr.",
    date_of_birth: "04/04/1965",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90001",
    },
    identification_number: "USA77788899",
    email: "robert@downey.com",
    phone_number: "+19992223333",
    emergency_contact: {
      first_name: "Susan",
      last_name: "Downey",
      phone_number: "+19994445555",
    },
    room_numbers: [8],
    check_in: "12/01/2023",
    check_out: "03/15/2024",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1400,
    vehicle: {
      make: "Mercedes",
      model: "S-Class",
      plate_number: "MBZ 456",
    },
  },
  {
    tenant_id: 1,
    first_name: "Emma",
    last_name: "Watson",
    date_of_birth: "04/15/1990",
    nationality: "British",
    address: {
      country: "United States",
      state: "California",
      city: "San Francisco",
      postal_code: "94101",
    },
    identification_number: "BRI98765432",
    email: "emma@watson.com",
    phone_number: "+17775554444",
    emergency_contact: {
      first_name: "Alex",
      last_name: "Watson",
      phone_number: "+17776665555",
    },
    room_numbers: [25, 26],
    check_in: "10/05/2023",
    check_out: "12/20/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1000,
    vehicle: {
      make: "Audi",
      model: "Q7",
      plate_number: "AUD 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Chris",
    last_name: "Hemsworth",
    date_of_birth: "08/11/1983",
    nationality: "Australian",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90002",
    },
    identification_number: "AUS12345678",
    email: "chris@hemsworth.com",
    phone_number: "+18886665555",
    emergency_contact: {
      first_name: "Liam",
      last_name: "Hemsworth",
      phone_number: "+18887776666",
    },
    room_numbers: [14],
    check_in: "07/10/2023",
    check_out: "09/25/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 950,
    vehicle: {
      make: "Lexus",
      model: "RX",
      plate_number: "LEX 321",
    },
  },
  {
    tenant_id: 1,
    first_name: "Scarlett",
    last_name: "Johansson",
    date_of_birth: "11/22/1984",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90003",
    },
    identification_number: "USA33322211",
    email: "scarlett@johansson.com",
    phone_number: "+19994443333",
    emergency_contact: {
      first_name: "Hunter",
      last_name: "Johansson",
      phone_number: "+19995554444",
    },
    room_numbers: [10, 11],
    check_in: "04/15/2023",
    check_out: "07/30/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 850,
    vehicle: {
      make: "Volvo",
      model: "XC90",
      plate_number: "VOL 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Mark",
    last_name: "Ruffalo",
    date_of_birth: "11/22/1967",
    nationality: "American",
    address: {
      country: "United States",
      state: "New York",
      city: "New York",
      postal_code: "10002",
    },
    identification_number: "USA11223344",
    email: "mark@ruffalo.com",
    phone_number: "+15552221111",
    emergency_contact: {
      first_name: "Sunrise",
      last_name: "Coigney",
      phone_number: "+15553334444",
    },
    room_numbers: [18, 19],
    check_in: "03/20/2023",
    check_out: "06/05/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 900,
    vehicle: {
      make: "Tesla",
      model: "Model X",
      plate_number: "TES 987",
    },
  },
  {
    tenant_id: 1,
    first_name: "Natalie",
    last_name: "Portman",
    date_of_birth: "06/09/1981",
    nationality: "Israeli",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90004",
    },
    identification_number: "ISR22334455",
    email: "natalie@portman.com",
    phone_number: "+17772221111",
    emergency_contact: {
      first_name: "Benjamin",
      last_name: "Millepied",
      phone_number: "+17773334444",
    },
    room_numbers: [1, 2],
    check_in: "01/10/2023",
    check_out: "04/25/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1300,
    vehicle: {
      make: "Jaguar",
      model: "F-Pace",
      plate_number: "JAG 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Brad",
    last_name: "Pitt",
    date_of_birth: "12/18/1963",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Hollywood",
      postal_code: "90028",
    },
    identification_number: "USA99887766",
    email: "brad@pitt.com",
    phone_number: "+18881112222",
    emergency_contact: {
      first_name: "Angelina",
      last_name: "Jolie",
      phone_number: "+18882223333",
    },
    room_numbers: [5, 6],
    check_in: "07/01/2023",
    check_out: "10/10/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1200,
    vehicle: {
      make: "Cadillac",
      model: "Escalade",
      plate_number: "CAD 321",
    },
  },
  {
    tenant_id: 1,
    first_name: "Leonardo",
    last_name: "DiCaprio",
    date_of_birth: "11/11/1974",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90005",
    },
    identification_number: "USA77766655",
    email: "leo@dicaprio.com",
    phone_number: "+19993334444",
    emergency_contact: {
      first_name: "George",
      last_name: "DiCaprio",
      phone_number: "+19994445555",
    },
    room_numbers: [20],
    check_in: "03/01/2023",
    check_out: "05/10/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1000,
    vehicle: {
      make: "Lamborghini",
      model: "Huracan",
      plate_number: "LAM 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Meryl",
    last_name: "Streep",
    date_of_birth: "06/22/1949",
    nationality: "American",
    address: {
      country: "United States",
      state: "New York",
      city: "New York",
      postal_code: "10001",
    },
    identification_number: "USA55544433",
    email: "meryl@streep.com",
    phone_number: "+15554443333",
    emergency_contact: {
      first_name: "Don",
      last_name: "Gummer",
      phone_number: "+15556667777",
    },
    room_numbers: [15, 16],
    check_in: "08/20/2023",
    check_out: "11/30/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1500,
    vehicle: {
      make: "Volvo",
      model: "XC60",
      plate_number: "VOL 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Tom",
    last_name: "Hanks",
    date_of_birth: "07/09/1956",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90006",
    },
    identification_number: "USA66655544",
    email: "tom@hanks.com",
    phone_number: "+16664443333",
    emergency_contact: {
      first_name: "Rita",
      last_name: "Wilson",
      phone_number: "+16667778888",
    },
    room_numbers: [12],
    check_in: "04/01/2023",
    check_out: "07/15/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 900,
    vehicle: {
      make: "Toyota",
      model: "Camry",
      plate_number: "TOY 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Morgan",
    last_name: "Freeman",
    date_of_birth: "06/01/1937",
    nationality: "American",
    address: {
      country: "United States",
      state: "Mississippi",
      city: "Charleston",
      postal_code: "38921",
    },
    identification_number: "USA33355522",
    email: "morgan@freeman.com",
    phone_number: "+12223334444",
    emergency_contact: {
      first_name: "Saifoulaye",
      last_name: "Freeman",
      phone_number: "+12226667777",
    },
    room_numbers: [8, 9],
    check_in: "05/20/2023",
    check_out: "08/10/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1100,
    vehicle: {
      make: "Lexus",
      model: "LS",
      plate_number: "LEX 987",
    },
  },
  {
    tenant_id: 1,
    first_name: "Natalie",
    last_name: "Portman",
    date_of_birth: "06/09/1981",
    nationality: "Israeli",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90004",
    },
    identification_number: "ISR22334455",
    email: "natalie@portman.com",
    phone_number: "+17772221111",
    emergency_contact: {
      first_name: "Benjamin",
      last_name: "Millepied",
      phone_number: "+17773334444",
    },
    room_numbers: [1, 2],
    check_in: "01/10/2023",
    check_out: "04/25/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1300,
    vehicle: {
      make: "Jaguar",
      model: "F-Pace",
      plate_number: "JAG 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Brad",
    last_name: "Pitt",
    date_of_birth: "12/18/1963",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Hollywood",
      postal_code: "90028",
    },
    identification_number: "USA99887766",
    email: "brad@pitt.com",
    phone_number: "+18881112222",
    emergency_contact: {
      first_name: "Angelina",
      last_name: "Jolie",
      phone_number: "+18882223333",
    },
    room_numbers: [5, 6],
    check_in: "07/01/2023",
    check_out: "10/10/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1200,
    vehicle: {
      make: "Cadillac",
      model: "Escalade",
      plate_number: "CAD 321",
    },
  },
  {
    tenant_id: 1,
    first_name: "Leonardo",
    last_name: "DiCaprio",
    date_of_birth: "11/11/1974",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90005",
    },
    identification_number: "USA77766655",
    email: "leo@dicaprio.com",
    phone_number: "+19993334444",
    emergency_contact: {
      first_name: "George",
      last_name: "DiCaprio",
      phone_number: "+19994445555",
    },
    room_numbers: [20],
    check_in: "03/01/2023",
    check_out: "05/10/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1000,
    vehicle: {
      make: "Lamborghini",
      model: "Huracan",
      plate_number: "LAM 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Meryl",
    last_name: "Streep",
    date_of_birth: "06/22/1949",
    nationality: "American",
    address: {
      country: "United States",
      state: "New York",
      city: "New York",
      postal_code: "10001",
    },
    identification_number: "USA55544433",
    email: "meryl@streep.com",
    phone_number: "+15554443333",
    emergency_contact: {
      first_name: "Don",
      last_name: "Gummer",
      phone_number: "+15556667777",
    },
    room_numbers: [15, 16],
    check_in: "08/20/2023",
    check_out: "11/30/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1500,
    vehicle: {
      make: "Volvo",
      model: "XC60",
      plate_number: "VOL 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Tom",
    last_name: "Hanks",
    date_of_birth: "07/09/1956",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90006",
    },
    identification_number: "USA66655544",
    email: "tom@hanks.com",
    phone_number: "+16664443333",
    emergency_contact: {
      first_name: "Rita",
      last_name: "Wilson",
      phone_number: "+16667778888",
    },
    room_numbers: [12],
    check_in: "04/01/2023",
    check_out: "07/15/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 900,
    vehicle: {
      make: "Toyota",
      model: "Camry",
      plate_number: "TOY 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Morgan",
    last_name: "Freeman",
    date_of_birth: "06/01/1937",
    nationality: "American",
    address: {
      country: "United States",
      state: "Mississippi",
      city: "Charleston",
      postal_code: "38921",
    },
    identification_number: "USA33355522",
    email: "morgan@freeman.com",
    phone_number: "+12223334444",
    emergency_contact: {
      first_name: "Saifoulaye",
      last_name: "Freeman",
      phone_number: "+12226667777",
    },
    room_numbers: [8, 9],
    check_in: "05/20/2023",
    check_out: "08/10/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1100,
    vehicle: {
      make: "Lexus",
      model: "LS",
      plate_number: "LEX 987",
    },
  },
  {
    tenant_id: 1,
    first_name: "Natalie",
    last_name: "Portman",
    date_of_birth: "06/09/1981",
    nationality: "Israeli",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90004",
    },
    identification_number: "ISR22334455",
    email: "natalie@portman.com",
    phone_number: "+17772221111",
    emergency_contact: {
      first_name: "Benjamin",
      last_name: "Millepied",
      phone_number: "+17773334444",
    },
    room_numbers: [1, 2],
    check_in: "01/10/2023",
    check_out: "04/25/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1300,
    vehicle: {
      make: "Jaguar",
      model: "F-Pace",
      plate_number: "JAG 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Brad",
    last_name: "Pitt",
    date_of_birth: "12/18/1963",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Hollywood",
      postal_code: "90028",
    },
    identification_number: "USA99887766",
    email: "brad@pitt.com",
    phone_number: "+18881112222",
    emergency_contact: {
      first_name: "Angelina",
      last_name: "Jolie",
      phone_number: "+18882223333",
    },
    room_numbers: [5, 6],
    check_in: "07/01/2023",
    check_out: "10/10/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1200,
    vehicle: {
      make: "Cadillac",
      model: "Escalade",
      plate_number: "CAD 321",
    },
  },
  {
    tenant_id: 1,
    first_name: "Leonardo",
    last_name: "DiCaprio",
    date_of_birth: "11/11/1974",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90005",
    },
    identification_number: "USA77766655",
    email: "leo@dicaprio.com",
    phone_number: "+19993334444",
    emergency_contact: {
      first_name: "George",
      last_name: "DiCaprio",
      phone_number: "+19994445555",
    },
    room_numbers: [20],
    check_in: "03/01/2023",
    check_out: "05/10/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1000,
    vehicle: {
      make: "Lamborghini",
      model: "Huracan",
      plate_number: "LAM 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Nicole",
    last_name: "Kidman",
    date_of_birth: "06/20/1967",
    nationality: "Australian",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90007",
    },
    identification_number: "AUS98765432",
    email: "nicole@kidman.com",
    phone_number: "+16661112222",
    emergency_contact: {
      first_name: "Keith",
      last_name: "Urban",
      phone_number: "+16662223333",
    },
    room_numbers: [13, 14],
    check_in: "05/05/2023",
    check_out: "08/15/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 950,
    vehicle: {
      make: "Audi",
      model: "Q7",
      plate_number: "AUD 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Hugh",
    last_name: "Jackman",
    date_of_birth: "10/12/1968",
    nationality: "Australian",
    address: {
      country: "United States",
      state: "New York",
      city: "New York",
      postal_code: "10003",
    },
    identification_number: "AUS22334455",
    email: "hugh@jackman.com",
    phone_number: "+14445556666",
    emergency_contact: {
      first_name: "Deborra-Lee",
      last_name: "Furness",
      phone_number: "+14446667777",
    },
    room_numbers: [17, 18],
    check_in: "04/20/2023",
    check_out: "07/30/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1200,
    vehicle: {
      make: "Range Rover",
      model: "Sport",
      plate_number: "RR 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Charlize",
    last_name: "Theron",
    date_of_birth: "08/07/1975",
    nationality: "South African",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90008",
    },
    identification_number: "SAF12345678",
    email: "charlize@theron.com",
    phone_number: "+15553334444",
    emergency_contact: {
      first_name: "Jackson",
      last_name: "Theron",
      phone_number: "+15556667777",
    },
    room_numbers: [22, 23],
    check_in: "06/01/2023",
    check_out: "09/10/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1100,
    vehicle: {
      make: "Tesla",
      model: "Model S",
      plate_number: "TES 321",
    },
  },
  {
    tenant_id: 1,
    first_name: "George",
    last_name: "Clooney",
    date_of_birth: "05/06/1961",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Beverly Hills",
      postal_code: "90210",
    },
    identification_number: "USA55533322",
    email: "george@clooney.com",
    phone_number: "+18883334444",
    emergency_contact: {
      first_name: "Amal",
      last_name: "Clooney",
      phone_number: "+18887778888",
    },
    room_numbers: [24, 25],
    check_in: "07/15/2023",
    check_out: "10/25/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1500,
    vehicle: {
      make: "BMW",
      model: "i8",
      plate_number: "BMW 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Sandra",
    last_name: "Bullock",
    date_of_birth: "07/26/1964",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90009",
    },
    identification_number: "USA11122233",
    email: "sandra@bullock.com",
    phone_number: "+16667778888",
    emergency_contact: {
      first_name: "Bryan",
      last_name: "Randall",
      phone_number: "+16669990000",
    },
    room_numbers: [26],
    check_in: "03/20/2023",
    check_out: "06/30/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1200,
    vehicle: {
      make: "Mercedes",
      model: "GLS",
      plate_number: "MBZ 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Matt",
    last_name: "Damon",
    date_of_birth: "10/08/1970",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90010",
    },
    identification_number: "USA99988877",
    email: "matt@damon.com",
    phone_number: "+14445556666",
    emergency_contact: {
      first_name: "Luciana",
      last_name: "Barroso",
      phone_number: "+14446667777",
    },
    room_numbers: [21, 22],
    check_in: "08/01/2023",
    check_out: "11/10/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1300,
    vehicle: {
      make: "Tesla",
      model: "Model X",
      plate_number: "TES 987",
    },
  },
  {
    tenant_id: 1,
    first_name: "Angelina",
    last_name: "Jolie",
    date_of_birth: "06/04/1975",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90011",
    },
    identification_number: "USA88877766",
    email: "angelina@jolie.com",
    phone_number: "+15553334444",
    emergency_contact: {
      first_name: "Maddox",
      last_name: "Jolie-Pitt",
      phone_number: "+15556667777",
    },
    room_numbers: [27, 28],
    check_in: "04/10/2023",
    check_out: "07/20/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1400,
    vehicle: {
      make: "Range Rover",
      model: "Evoque",
      plate_number: "RR 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Jennifer",
    last_name: "Aniston",
    date_of_birth: "02/11/1969",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90012",
    },
    identification_number: "USA33322211",
    email: "jennifer@aniston.com",
    phone_number: "+12223334444",
    emergency_contact: {
      first_name: "Courteney",
      last_name: "Cox",
      phone_number: "+12226667777",
    },
    room_numbers: [19],
    check_in: "09/15/2023",
    check_out: "12/25/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1300,
    vehicle: {
      make: "BMW",
      model: "X5",
      plate_number: "BMW 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Dwayne",
    last_name: "Johnson",
    date_of_birth: "05/02/1972",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90013",
    },
    identification_number: "USA11122233",
    email: "dwayne@johnson.com",
    phone_number: "+17776665555",
    emergency_contact: {
      first_name: "Lauren",
      last_name: "Hashian",
      phone_number: "+17779990000",
    },
    room_numbers: [29, 30],
    check_in: "02/01/2023",
    check_out: "05/15/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1000,
    vehicle: {
      make: "Ford",
      model: "F-150",
      plate_number: "FRD 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Reese",
    last_name: "Witherspoon",
    date_of_birth: "03/22/1976",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90014",
    },
    identification_number: "USA44433322",
    email: "reese@witherspoon.com",
    phone_number: "+16667778888",
    emergency_contact: {
      first_name: "Jim",
      last_name: "Toth",
      phone_number: "+16669990000",
    },
    room_numbers: [23, 24],
    check_in: "06/10/2023",
    check_out: "09/20/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1400,
    vehicle: {
      make: "Tesla",
      model: "Model 3",
      plate_number: "TES 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Ryan",
    last_name: "Reynolds",
    date_of_birth: "10/23/1976",
    nationality: "Canadian",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90015",
    },
    identification_number: "CAN12345678",
    email: "ryan@reynolds.com",
    email: "ryan@reynolds.com",
    phone_number: "+17775554444",
    emergency_contact: {
      first_name: "Blake",
      last_name: "Lively",
      phone_number: "+17776665555",
    },
    room_numbers: [31, 32],
    check_in: "04/15/2023",
    check_out: "07/25/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1500,
    vehicle: {
      make: "Ferrari",
      model: "458",
      plate_number: "FER 321",
    },
  },
  {
    tenant_id: 1,
    first_name: "Scarlett",
    last_name: "Johansson",
    date_of_birth: "11/22/1984",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90003",
    },
    identification_number: "USA33322211",
    email: "scarlett@johansson.com",
    phone_number: "+19994443333",
    emergency_contact: {
      first_name: "Hunter",
      last_name: "Johansson",
      phone_number: "+19995554444",
    },
    room_numbers: [10, 11],
    check_in: "04/15/2023",
    check_out: "07/30/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 850,
    vehicle: {
      make: "Volvo",
      model: "XC90",
      plate_number: "VOL 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Chris",
    last_name: "Hemsworth",
    date_of_birth: "08/11/1983",
    nationality: "Australian",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90002",
    },
    identification_number: "AUS12345678",
    email: "chris@hemsworth.com",
    phone_number: "+18886665555",
    emergency_contact: {
      first_name: "Liam",
      last_name: "Hemsworth",
      phone_number: "+18887776666",
    },
    room_numbers: [14],
    check_in: "07/10/2023",
    check_out: "09/25/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 950,
    vehicle: {
      make: "Lexus",
      model: "RX",
      plate_number: "LEX 321",
    },
  },
  {
    tenant_id: 1,
    first_name: "Emma",
    last_name: "Watson",
    date_of_birth: "04/15/1990",
    nationality: "British",
    address: {
      country: "United States",
      state: "California",
      city: "San Francisco",
      postal_code: "94101",
    },
    identification_number: "BRI98765432",
    email: "emma@watson.com",
    phone_number: "+17775554444",
    emergency_contact: {
      first_name: "Alex",
      last_name: "Watson",
      phone_number: "+17776665555",
    },
    room_numbers: [25, 26],
    check_in: "10/05/2023",
    check_out: "12/20/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1000,
    vehicle: {
      make: "Audi",
      model: "Q7",
      plate_number: "AUD 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Tom",
    last_name: "Cruise",
    date_of_birth: "07/03/1962",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Beverly Hills",
      postal_code: "90210",
    },
    identification_number: "USA98765432",
    email: "tom@cruise.com",
    phone_number: "+15553334444",
    emergency_contact: {
      first_name: "Isabella",
      last_name: "Cruise",
      phone_number: "+15556667777",
    },
    room_numbers: [27],
    check_in: "09/20/2023",
    check_out: "12/31/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1450,
    vehicle: {
      make: "BMW",
      model: "M3",
      plate_number: "BMW 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Will",
    last_name: "Smith",
    date_of_birth: "09/25/1968",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Calabasas",
      postal_code: "91302",
    },
    identification_number: "USA87654321",
    email: "will@smith.com",
    phone_number: "+16665554444",
    emergency_contact: {
      first_name: "Jada",
      last_name: "Pinkett-Smith",
      phone_number: "+16667778888",
    },
    room_numbers: [28, 29],
    check_in: "11/10/2023",
    check_out: "02/15/2024",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1600,
    vehicle: {
      make: "Mercedes",
      model: "G-Wagon",
      plate_number: "MBZ 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Gal",
    last_name: "Gadot",
    date_of_birth: "04/30/1985",
    nationality: "Israeli",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90001",
    },
    identification_number: "ISR54321098",
    email: "gal@gadot.com",
    phone_number: "+14443332222",
    emergency_contact: {
      first_name: "Yaron",
      last_name: "Varsano",
      phone_number: "+14445556666",
    },
    room_numbers: [30, 31],
    check_in: "08/15/2023",
    check_out: "11/25/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1500,
    vehicle: {
      make: "Cadillac",
      model: "CT6",
      plate_number: "CAD 456",
    },
  },
  {
    tenant_id: 1,
    first_name: "Zoe",
    last_name: "Saldana",
    date_of_birth: "06/19/1978",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90002",
    },
    identification_number: "USA98765432",
    email: "zoe@saldana.com",
    phone_number: "+15554443333",
    emergency_contact: {
      first_name: "Marco",
      last_name: "Perego",
      phone_number: "+15556667777",
    },
    room_numbers: [32, 33],
    check_in: "06/01/2023",
    check_out: "09/10/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1400,
    vehicle: {
      make: "Audi",
      model: "A7",
      plate_number: "AUD 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Chris",
    last_name: "Pratt",
    date_of_birth: "06/21/1979",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90003",
    },
    identification_number: "USA56789012",
    email: "chris@pratt.com",
    phone_number: "+16663332222",
    emergency_contact: {
      first_name: "Katherine",
      last_name: "Schwarzenegger",
      phone_number: "+16664445555",
    },
    room_numbers: [33, 34],
    check_in: "05/15/2023",
    check_out: "08/25/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1200,
    vehicle: {
      make: "Ford",
      model: "Explorer",
      plate_number: "FRD 456",
    },
  },
  {
    tenant_id: 1,
    first_name: "Vin",
    last_name: "Diesel",
    date_of_birth: "07/18/1967",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90004",
    },
    identification_number: "USA34567890",
    email: "vin@diesel.com",
    phone_number: "+17774443333",
    emergency_contact: {
      first_name: "Paloma",
      last_name: "Jimenez",
      phone_number: "+17775554444",
    },
    room_numbers: [35, 36],
    check_in: "06/10/2023",
    check_out: "09/20/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1100,
    vehicle: {
      make: "Dodge",
      model: "Charger",
      plate_number: "DOG 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Anne",
    last_name: "Hathaway",
    date_of_birth: "11/12/1982",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90005",
    },
    identification_number: "USA67890123",
    email: "anne@hathaway.com",
    phone_number: "+18885554444",
    emergency_contact: {
      first_name: "Adam",
      last_name: "Shulman",
      phone_number: "+18886665555",
    },
    room_numbers: [37, 38],
    check_in: "07/20/2023",
    check_out: "10/30/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1300,
    vehicle: {
      make: "Audi",
      model: "Q5",
      plate_number: "AUD 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Robert",
    last_name: "Pattinson",
    date_of_birth: "05/13/1986",
    nationality: "British",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90006",
    },
    identification_number: "UK54321098",
    email: "robert@pattinson.com",
    phone_number: "+14443332222",
    emergency_contact: {
      first_name: "Suki",
      last_name: "Waterhouse",
      phone_number: "+14445556666",
    },
    room_numbers: [39],
    check_in: "03/05/2023",
    check_out: "06/15/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1000,
    vehicle: {
      make: "BMW",
      model: "X6",
      plate_number: "BMW 321",
    },
  },
  {
    tenant_id: 1,
    first_name: "Margot",
    last_name: "Robbie",
    date_of_birth: "07/02/1990",
    nationality: "Australian",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90007",
    },
    identification_number: "AUS54321098",
    email: "margot@robbie.com",
    phone_number: "+16662223333",
    emergency_contact: {
      first_name: "Tom",
      last_name: "Ackerley",
      phone_number: "+16663334444",
    },
    room_numbers: [40, 41],
    check_in: "04/25/2023",
    check_out: "08/05/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1150,
    vehicle: {
      make: "Tesla",
      model: "Model Y",
      plate_number: "TES 456",
    },
  },
  {
    tenant_id: 1,
    first_name: "Zendaya",
    last_name: "Coleman",
    date_of_birth: "09/01/1996",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Oakland",
      postal_code: "94601",
    },
    identification_number: "USA76543210",
    email: "zendaya@coleman.com",
    phone_number: "+18884443333",
    emergency_contact: {
      first_name: "Claire",
      last_name: "Stoermer",
      phone_number: "+18885554444",
    },
    room_numbers: [42],
    check_in: "01/15/2024",
    check_out: "04/30/2024",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1300,
    vehicle: {
      make: "Mercedes",
      model: "GLA",
      plate_number: "MBZ 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Timothée",
    last_name: "Chalamet",
    date_of_birth: "12/27/1995",
    nationality: "American",
    address: {
      country: "United States",
      state: "New York",
      city: "New York",
      postal_code: "10001",
    },
    identification_number: "USA87654321",
    email: "timothee@chalamet.com",
    phone_number: "+17772223333",
    emergency_contact: {
      first_name: "Nicole",
      last_name: "Flender",
      phone_number: "+17773334444",
    },
    room_numbers: [43, 44],
    check_in: "03/10/2023",
    check_out: "06/20/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1250,
    vehicle: {
      make: "Chevrolet",
      model: "Suburban",
      plate_number: "CHE 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Florence",
    last_name: "Pugh",
    date_of_birth: "01/03/1996",
    nationality: "British",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90008",
    },
    identification_number: "UK65432109",
    email: "florence@pugh.com",
    phone_number: "+15553332222",
    emergency_contact: {
      first_name: "Clinton",
      last_name: "Pugh",
      phone_number: "+15554443333",
    },
    room_numbers: [45],
    check_in: "02/01/2024",
    check_out: "05/15/2024",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1400,
    vehicle: {
      make: "Ford",
      model: "Mustang",
      plate_number: "FRD 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Benedict",
    last_name: "Cumberbatch",
    date_of_birth: "07/19/1976",
    nationality: "British",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90009",
    },
    identification_number: "UK12345678",
    email: "benedict@cumberbatch.com",
    phone_number: "+16664443333",
    emergency_contact: {
      first_name: "Sophie",
      last_name: "Hunter",
      phone_number: "+16665554444",
    },
    room_numbers: [46, 47],
    check_in: "01/15/2023",
    check_out: "04/25/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1100,
    vehicle: {
      make: "Jaguar",
      model: "F-Type",
      plate_number: "JAG 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Tom",
    last_name: "Hiddleston",
    date_of_birth: "02/09/1981",
    nationality: "British",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90010",
    },
    identification_number: "UK87654321",
    email: "tom@hiddleston.com",
    phone_number: "+14442223333",
    emergency_contact: {
      first_name: "Zawe",
      last_name: "Ashton",
      phone_number: "+14443334444",
    },
    room_numbers: [48],
    check_in: "03/01/2023",
    check_out: "06/10/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1250,
    vehicle: {
      make: "Aston Martin",
      model: "DB11",
      plate_number: "AST 456",
    },
  },
  {
    tenant_id: 1,
    first_name: "Daniel",
    last_name: "Craig",
    date_of_birth: "03/02/1968",
    nationality: "British",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90011",
    },
    identification_number: "UK65432109",
    email: "daniel@craig.com",
    phone_number: "+15553332222",
    emergency_contact: {
      first_name: "Rachel",
      last_name: "Weisz",
      phone_number: "+15554443333",
    },
    room_numbers: [49],
    check_in: "04/10/2023",
    check_out: "07/20/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1400,
    vehicle: {
      make: "Bentley",
      model: "Continental",
      plate_number: "BEN 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Emma",
    last_name: "Stone",
    date_of_birth: "11/06/1988",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90001",
    },
    identification_number: "USA87654321",
    email: "emma@stone.com",
    phone_number: "+16667778888",
    emergency_contact: {
      first_name: "Andrew",
      last_name: "Garfield",
      phone_number: "+16669990000",
    },
    room_numbers: [30],
    check_in: "06/15/2023",
    check_out: "08/20/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 900,
    vehicle: {
      make: "BMW",
      model: "X5",
      plate_number: "BMW 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Michael",
    last_name: "Jordan",
    date_of_birth: "02/17/1963",
    nationality: "American",
    address: {
      country: "United States",
      state: "Illinois",
      city: "Chicago",
      postal_code: "60616",
    },
    identification_number: "USA99988877",
    email: "michael@jordan.com",
    phone_number: "+14443332222",
    emergency_contact: {
      first_name: "Scottie",
      last_name: "Pippen",
      phone_number: "+14446665555",
    },
    room_numbers: [7, 8, 9],
    check_in: "03/10/2023",
    check_out: "07/15/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 750,
    vehicle: {
      make: "Mercedes",
      model: "S-Class",
      plate_number: "MBZ 456",
    },
  },
  {
    tenant_id: 1,
    first_name: "Taylor",
    last_name: "Swift",
    date_of_birth: "12/13/1989",
    nationality: "American",
    address: {
      country: "United States",
      state: "Tennessee",
      city: "Nashville",
      postal_code: "37201",
    },
    identification_number: "USA11122233",
    email: "taylor@swift.com",
    phone_number: "+17778889999",
    emergency_contact: {
      first_name: "Austin",
      last_name: "Swift",
      phone_number: "+17770001111",
    },
    room_numbers: [45, 46],
    check_in: "09/01/2023",
    check_out: "11/30/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1300,
    vehicle: {
      make: "Audi",
      model: "A8",
      plate_number: "AUD 321",
    },
  },
  {
    tenant_id: 1,
    first_name: "Chris",
    last_name: "Evans",
    date_of_birth: "06/13/1981",
    nationality: "American",
    address: {
      country: "United States",
      state: "Massachusetts",
      city: "Boston",
      postal_code: "02101",
    },
    identification_number: "USA55566677",
    email: "chris@evans.com",
    phone_number: "+18889990000",
    emergency_contact: {
      first_name: "Scott",
      last_name: "Evans",
      phone_number: "+18880002222",
    },
    room_numbers: [12],
    check_in: "05/22/2023",
    check_out: "09/12/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1100,
    vehicle: {
      make: "Chevrolet",
      model: "Impala",
      plate_number: "CHE 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Jennifer",
    last_name: "Lawrence",
    date_of_birth: "08/15/1990",
    nationality: "American",
    address: {
      country: "United States",
      state: "Kentucky",
      city: "Louisville",
      postal_code: "40201",
    },
    identification_number: "USA33344455",
    email: "jennifer@lawrence.com",
    phone_number: "+19991112222",
    emergency_contact: {
      first_name: "Blaine",
      last_name: "Lawrence",
      phone_number: "+19990003333",
    },
    room_numbers: [3, 4],
    check_in: "11/10/2023",
    check_out: "02/20/2024",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 800,
    vehicle: {
      make: "Ford",
      model: "Explorer",
      plate_number: "FRD 123",
    },
  },
  {
    tenant_id: 1,
    first_name: "Robert",
    last_name: "Downey Jr.",
    date_of_birth: "04/04/1965",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90001",
    },
    identification_number: "USA77788899",
    email: "robert@downey.com",
    phone_number: "+19992223333",
    emergency_contact: {
      first_name: "Susan",
      last_name: "Downey",
      phone_number: "+19994445555",
    },
    room_numbers: [8],
    check_in: "12/01/2023",
    check_out: "03/15/2024",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1400,
    vehicle: {
      make: "Mercedes",
      model: "S-Class",
      plate_number: "MBZ 456",
    },
  },
  {
    tenant_id: 1,
    first_name: "Chris",
    last_name: "Hemsworth",
    date_of_birth: "08/11/1983",
    nationality: "Australian",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90002",
    },
    identification_number: "AUS12345678",
    email: "chris@hemsworth.com",
    phone_number: "+18886665555",
    emergency_contact: {
      first_name: "Liam",
      last_name: "Hemsworth",
      phone_number: "+18887776666",
    },
    room_numbers: [14],
    check_in: "07/10/2023",
    check_out: "09/25/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 950,
    vehicle: {
      make: "Lexus",
      model: "RX",
      plate_number: "LEX 321",
    },
  },
  {
    tenant_id: 1,
    first_name: "Emma",
    last_name: "Watson",
    date_of_birth: "04/15/1990",
    nationality: "British",
    address: {
      country: "United States",
      state: "California",
      city: "San Francisco",
      postal_code: "94101",
    },
    identification_number: "BRI98765432",
    email: "emma@watson.com",
    phone_number: "+17775554444",
    emergency_contact: {
      first_name: "Alex",
      last_name: "Watson",
      phone_number: "+17776665555",
    },
    room_numbers: [25, 26],
    check_in: "10/05/2023",
    check_out: "12/20/2023",
    payment_method: "transfer",
    payment_status: "failed",
    total_amount: 1000,
    vehicle: {
      make: "Audi",
      model: "Q7",
      plate_number: "AUD 654",
    },
  },
  {
    tenant_id: 1,
    first_name: "Scarlett",
    last_name: "Johansson",
    date_of_birth: "11/22/1984",
    nationality: "American",
    address: {
      country: "United States",
      state: "California",
      city: "Los Angeles",
      postal_code: "90003",
    },
    identification_number: "USA33322211",
    email: "scarlett@johansson.com",
    phone_number: "+19994443333",
    emergency_contact: {
      first_name: "Hunter",
      last_name: "Johansson",
      phone_number: "+19995554444",
    },
    room_numbers: [10, 11],
    check_in: "04/15/2023",
    check_out: "07/30/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 850,
    vehicle: {
      make: "Volvo",
      model: "XC90",
      plate_number: "VOL 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Chris",
    last_name: "Evans",
    date_of_birth: "06/13/1981",
    nationality: "American",
    address: {
      country: "United States",
      state: "Massachusetts",
      city: "Boston",
      postal_code: "02101",
    },
    identification_number: "USA55566677",
    email: "chris@evans.com",
    phone_number: "+18889990000",
    emergency_contact: {
      first_name: "Scott",
      last_name: "Evans",
      phone_number: "+18880002222",
    },
    room_numbers: [12],
    check_in: "05/22/2023",
    check_out: "09/12/2023",
    payment_method: "cash",
    payment_status: "pending",
    total_amount: 1100,
    vehicle: {
      make: "Chevrolet",
      model: "Impala",
      plate_number: "CHE 789",
    },
  },
  {
    tenant_id: 1,
    first_name: "Taylor",
    last_name: "Swift",
    date_of_birth: "12/13/1989",
    nationality: "American",
    address: {
      country: "United States",
      state: "Tennessee",
      city: "Nashville",
      postal_code: "37201",
    },
    identification_number: "USA11122233",
    email: "taylor@swift.com",
    phone_number: "+17778889999",
    emergency_contact: {
      first_name: "Austin",
      last_name: "Swift",
      phone_number: "+17770001111",
    },
    room_numbers: [45, 46],
    check_in: "09/01/2023",
    check_out: "11/30/2023",
    payment_method: "credit",
    payment_status: "completed",
    total_amount: 1300,
    vehicle: {
      make: "Audi",
      model: "A8",
      plate_number: "AUD 321",
    },
  },
];

module.exports = mockData;
